config/routes.rb
KtitengineeringCom::Application.routes.draw do

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'ktit_engineering#index'
  match 's' => "smarts#index", :via => :get, :as => :smart
  match 'counters/batch', :via => :get
  resources :services, :only => [] do
    collection do
      post :view
    end
  end
  resources :contacts, :only => [:index,:create,:new] do
    collection do
      post :view
      post :lodge
      post :smart_create
    end
  end
end

app/models/ktit_engineering.rb
class KtitEngineering < Template::Engineering
  
end

app/controllers/ktit_engineering_controller.rb
class KtitEngineeringController < ApplicationController

  layout 'engineering'

  def index
    redirect_to smart_path if Webcom::Browser.phone?(request, nil)
    @space = KtitEngineering.public.first
    @client = Client.find_by_namespace("ktit_engineering")
    logger.debug("Client: #{@client} space: #{@space}")
  end
  
  def service_view
    @service = Service.find(params[:id])
  end
  
end

app/views/ktit_engineering/_footer.html.erb
<div class="footer footer-color">
<div class="container">
	<!-- FOOTER -->
	<footer>
		<p>
			<%=image_tag("footer-logo_64.png", :class => "img-circle")%>&nbsp;&copy; K.T. IT Engineering 2013 ABN: 78631933118  Phone: 0433654800 &middot; <%= link_to_with_icon_remote(t("contact.us"), lodge_contacts_path(:id => "general", :locale => "#{I18n.locale}"), "", "", "icon-envelope-alt icon-spin", "footer-contactus", "post")%> &middot; <a href="#" id="to_about"><%= t("contact.about_us")%></a>
		</p>

<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.	</footer>
			<small style="text-shadow: none">Version: <%=Style::VERSION%></small>
<%= _script(%Q|
$('\#footer-contactus').click(function(){
	$('.contact-form').fadeIn("show");
	$('.contact-form').html('#{escape_javascript('<i class="icon-spinner icon-spin icon-2x"></i>')}');
	$('html, body').animate({scrollTop: $(".contact-form").offset().top}, 2000);
});
$('\#header-contactus').click(function(){
	$('.contact-form').fadeIn("show");
	$('.contact-form').html('#{escape_javascript('<i class="icon-spinner icon-spin icon-2x"></i>')}');
	$('html, body').animate({scrollTop: $(".contact-form").offset().top}, 2000);
});
$('\#to_about').click(function(){
	$('.about').fadeIn(2000);
	return false;
});
|)%>
</div>
</div>

app/views/ktit_engineering/_header.html.erb
<div class="navbar navbar-inverse">
	<div class="navbar-inner nav-color">
		<div class="container">
			<a class="brand" href="<%= root_path%>"><%= image_tag(@client.logo?, :class => "img-rounded") %>&nbsp;&nbsp;&nbsp; <i class="icon-quote-left muted"></i>&nbsp; <%= t("header.business_copy") %>&nbsp; <i class="icon-quote-right muted"></i></a>
			<ul class="nav pull-right">
				<% KtitengineeringCom::Application.config.available_language.each do |language| %>
					<% if I18n.locale.to_s.eql?(language) %>
					<li class="active">
					<% else %>
					<li>
					<% end %>
					<%= link_to_with_icon(t("lang.#{language}"), "#", "", "", "icon-flag","lang-#{language}")%>
					<%= _document_on("click","\#lang-#{language}",%Q|function(){
						$.mobile.loading( 'show', {
							text: '#{t("loading")}',
							textVisible: true,
							theme: 'c',
							html: ""
						});
						document.location.href="#{root_path(:locale => "#{language}")}"
						}
					|)
					%>
					</li>
				<% end %>
				<li><%= link_to_with_icon_remote(t("contact.us"), lodge_contacts_path(:id => "general", :locale => "#{I18n.locale}"), "", "", "icon-envelope-alt icon-spin", "header-contactus", "post")%></li>
			</ul>
		</div>
	</div>
</div>

app/views/ktit_engineering/_service_view.html.erb
<%= raw @service_content %> 
<%= link_to_with_icon_remote(t("contact.us"), lodge_contacts_path(:id => @service_id, :locale => I18n.locale), "btn btn-primary", "", "icon-envelope-alt", "service-contactus-#{@service_id}", "post")%>
<%= _script(%Q|
	$('\#service-contactus-#{@service_id}').click(function(){
		$('.contact-form').fadeIn("show");
		$('.contact-form').html('#{escape_javascript('<i class="icon-spinner icon-spin icon-2x"></i>')}');
		$('html, body').animate({scrollTop: $('.contact-form').offset().top}, 2000);
	});
|)%>

app/views/ktit_engineering/index.html.erb
<!-- Top -->
<% locale = I18n.locale.to_sym%>

<% if @space.present? %>
<div class="main box_round">
	<div class="alert alert-info">
		<h2 class="visible-desktop visible-tablet">&nbsp;<%= Style.get_flyer_text(locale)%></h2>
		<h4 class="visible-phone">&nbsp;<%= Style.get_flyer_text(locale)%></h4>
		<!-- %= image_tag(@space.image.last.original_image, :class => "image-resize140_120 page-header-img")% -->
	</div>

	<div class="container-fluid service-container">
		<div class="row-fluid">
			<div class="service-box">
				<% Style.get_services.each do |s| %>
				<% service = Style.get_service(locale, s)%>
				<div class="service box_round" id="service-<%= service[:id]%>" style="text-shadow:none;">
					<div class="service-view" id="service-view-<%= service[:id]%>">
						<h3 class="visible-desktop visible-tablet"><%= service[:headline] %>&nbsp;<i class="<%= service[:icon]%>"></i></h3>
						<h4 class="visible-phone"><i class="<%= service[:icon]%>"></i>&nbsp;<%= service[:headline] %></h4>
						<p class="visible-desktop visible-tablet lead">
							<%= service[:leadline] %>
						</p>
						<p class="visible-phone">
							<%= service[:leadline] %>
						</p>
						<%= _mobile_tap("service-view-#{service[:id]}",%Q|
							#{_mobile_loading(t("loading"),'c','')}
							$('\#contact-form-#{service[:id]}').html('');
							$('\#service-content-#{service[:id]}').toggle('slow');
													
							$('\#service-desc-#{service[:id]}').attr('style','margin:auto;visibility:visible');
							$('\#service-content-#{service[:id]}').html('#{escape_javascript('<i class="icon-spinner icon-spin icon-3x"></i>')}');
							#{Ajax::post(%Q|services/view|,%Q|id : '#{service[:id]}', locale : '#{I18n.locale}'|)}
						|)%>
					</div>
					<div class="service-content-<%= service[:id]%> box_round" id="service-desc-<%= service[:id]%>" style="visibility:hidden">
						<div class="service-content" id="service-content-<%= service[:id]%>" style="display:none"></div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	<div class="row-fluid">
		<div class="contact-form contact-form-desktop box_round" style="display:none;text-shadow:none;">

		</div>
	</div>
	<div class="row-fluid">
		<div class="box_round about" style="display:none;text-shadow:none;">
			<i class="icon-pushpin icon-3x pull-left wood-pushpin"></i>
			<%= link_to_with(t("op.close"),"#","pull-right btn btn-mini btn-primary","color:#ffffff","close")%>
			<%= _script(%Q|
			$('\#close').click(function(){
			$('.about').fadeOut(2000);
			return false;
			});
			|)%>
			<br>
			<%= raw(Cms.about(I18n.locale))%>
		</div>
	</div>
	</div>
</div>
<% end %>