config/routes.rb
KtitengineeringCom::Application.routes.draw do

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'ktit_engineering#index'
  match 's' => "smarts#index", :via => :get, :as => :smart
  match 'counters/batch', :via => :get
  resources :services, :only => [] do
    collection do
      post :view
    end
  end
  resources :contacts, :only => [:index,:create,:new] do
    collection do
      post :view
      post :lodge
      post :smart_create
    end
  end
end

app/controllers/smarts_controller.rb
class SmartsController < KtitEngineeringController
  
  layout "smart/application"
  
  before_filter :phone_user
  
  def phone_user
    logger.debug("phone_user")
    if Rails.env == "production"
      logger.info("Redirect to root_path")
      redirect_to root_path unless Webcom::Browser.phone?(request)
    end
  end

  def index
    @space = KtitEngineering.public.first
    @client = Client.find_by_namespace("ktit_engineering")
    logger.debug("Client: #{@client} space: #{@space}")
  end

end

app/views/smarts/index.html.erb
<!-- Top -->
<% locale = I18n.locale.to_sym%>

<% if @space.present? %>
<div class="" data-role="page" data-theme="c" id="main">
	<div class="" data-role="header"  >
		<div class="ui-grid-a">
			<div class="ui-block-a">
			<%= image_tag("ktit_logo_phone.png", :class => "") %></div>
			<div class="ui-block-b">
		<%= t("header.business_copy") %>

		</div>
				</div>
		<div data-role="navbar">
			<ul>
				<% KtitengineeringCom::Application.config.available_language.each do |language| %>
				<li>
					<%= link_to_with_icon(t("lang.#{language}"), "#", "", "", "icon-flag","lang-#{language}")%>
				</li>
				<%= _document_on("click","\#lang-#{language}",%Q|function(){
				$.mobile.loading( 'show', {
				text: '#{t("loading")}',
				textVisible: true,
				theme: 'c',
				html: ""
				});
				document.location.href="#{smart_path(:locale => "#{language}")}"
				}
				|) %>
				<% end %>
			</ul>
		</div><!-- /navbar -->


	</div>

	<div class="" data-role="content">
		<h2><%= Style.get_flyer_text(locale, :phone) %></h2>
		<ul data-role="listview" data-inset="false" data-filter="false">

			<% Style.get_services.each do |s| %>
			<% service = Style.get_service(locale, s)%>
			<li>
				<a href="#page-<%= service[:id]%>"><i class="<%= service[:icon]%>"></i>&nbsp;<%= service[:headline] %></a>
			</li>
			<% end %>
		</ul>

	</div>

	<div data-role="footer">
		<%= render :partial => "#{@client.namespace}/smarts/footer" %>
	</div>

</div>
<% Style.get_services.each do |s| %>
<% service = Style.get_service(locale, s)%>
<div class="" data-role="page" data-theme="a" id="page-<%= service[:id]%>">
	<div class="" data-role="header"><%= service[:leadline] %></div>
	<div class="" data-role="content">
		<%= raw Style.get_service_content(locale, s, :phone) %>
		<%= link_to_with_icon(t("contact.us"), new_contact_path(:id => service[:id], :locale => I18n.locale, :device => :phone), "button", "", "icon-envelope-alt", "service-contactus-#{service[:id]}")%>
	</div>

	<div data-role="footer">
		<a href="#main"　data-role="button"><%= t("op.back")%></a>
	</div>
</div>

<% end %>

<div class="" data-role="page" data-theme="c" id="about">
	<div class="" data-role="header"><%= t("contact.about_us")%></div>
	<div class="" data-role="content">
			<%= raw(Style.get_about(I18n.locale, :phone))%>
	</div>

	<div data-role="footer">
		<a href="<%= smart_path(:locale => I18n.locale)%>"　data-role="button"><%= t("op.back")%></a>
	</div>

</div>
<% end %>